services:
  messages:
    build: .   # Make image from Dockerfile in cwd
    ports:
      - 8086:8086  # Export port 8086

    environment:
          - MYSQL_HOST=mysql  # Set host to mysql service name

    env_file:
      - .env     # Get password from this file
    
    depends_on:  # Wait for MySQL to launch
      mysql:
        condition: service_healthy

  mysql:
    image: mysql   # Image name to run

    environment:   # Set env vars
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=messagesdb
      - MYSQL_USER=messagesuser

    env_file:
      - .env      # Get password from this file
    
    healthcheck:  # Test for MySQL health
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 2s  # Run every 2 seconds
      retries: 60  # Giving up after 60 tries


# docker run -d --rm \
# --name mysql-server \
# --network mysql-net \
# -e MYSQL_RANDOM_ROOT_PASSWORD=yes \
# --env-file .env \
# mysql

# docker run -it --rm \
# --name messages-app \
# --network mysql-net \
# --env-file .env \
# -p 8086:8086 \
# messages-app